<?xml version="1.0" encoding="UTF-8"?><testrun name="UrlValidatorTest" project="URLValidator" tests="5" started="5" failures="1" errors="0" ignored="0">
  <testsuite name="UrlValidatorTest" time="0.003">
    <testcase name="testManualTest" classname="UrlValidatorTest" time="0.0"/>
    <testcase name="testSuccessfullyWorkingAsExpected" classname="UrlValidatorTest" time="0.001">
      <failure>junit.framework.AssertionFailedError: http://www.google.com:8000/mail/?twenty=20&amp;UnitID=439 should be valid&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:22)&#13;
	at junit.framework.TestCase.assertTrue(TestCase.java:192)&#13;
	at UrlValidatorTest.testSuccessfullyWorkingAsExpected(UrlValidatorTest.java:92)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testSuccessfullyFailingAsExpected" classname="UrlValidatorTest" time="0.0"/>
    <testcase name="testShouldBeNotWorkingButAreWorking" classname="UrlValidatorTest" time="0.0"/>
    <testcase name="testShouldBeWorkingButAreNotWorking" classname="UrlValidatorTest" time="0.001"/>
  </testsuite>
</testrun>
